#!/usr/bin/env python3
"""handover -- write a plain-text spec sheet for a set of .plt files.

Intended to travel with the files when someone else operates the plotter. It
states what the files are and how they are scaled, so the operator does not
have to guess -- guessing is how a marker gets printed at the wrong size.
"""

import argparse
import os
import sys

from clo2plt import classify, hpglread

TEMPLATE = """\
PLOTTER FILE SPECIFICATION
{underline}

Format        HP-GL (plain, not HP-GL/2). Plain ASCII text.
Units         40 plotter units per millimetre (1016 per inch, 0.025 mm).
              This is the HP-GL default resolution.
Coordinates   Absolute (PA). Origin bottom-left. No scaling applied.
Scale         1:1. These are true garment pattern dimensions -- please do
              not fit-to-page, auto-scale, or rotate to fit.
Instructions  IN, PA, SP, PU, PD, LB, SI, DI, DT only. No HP-GL/2
              extensions (no PE, PW, TR), no arcs, no raster.

FILES
Each line shows the size the file plots at, and the minimum paper width it
needs. Files marked ALTERNATE are the same job turned 90 degrees -- print
one or the other, never both.

{files}
PEN ASSIGNMENT
Each pen carries one kind of pattern line. On a single-ink plotter they
will all print the same colour, which is expected -- the separation is so
that individual line types can be suppressed if you need that.

{pens}
ORIENTATION -- PLEASE READ
The HP-GL X axis must map ACROSS the paper width, and Y along the feed.
Each file's paper requirement is listed above; nothing here needs to be
rotated or scaled to fit.
{orient}
CHECK BEFORE PRINTING THE LARGE FILES
  * Please run "{cal}" first. It contains a 200 mm square.
    If it does not measure exactly 200 mm, something in the chain is
    rescaling, and every marker will be wrong by that same factor.
  * "{test}" is a single small pattern piece,
    996.6 x 180.0 mm. Worth running second to confirm orientation before
    committing a full marker.

Generated by clo2plt from CLO 3D PDF exports.
"""


def describe(path):
    with open(path, "r", encoding="latin-1") as fh:
        drawing = hpglread.parse(fh.read())
    box = drawing.bbox
    if box is None:
        return None, 0.0
    points = sum(len(p.points) for p in drawing.polylines)
    ntext = len(drawing.texts)
    name = os.path.basename(path)
    w, h = box[2] - box[0], box[3] - box[1]
    stats = (f"      {len(drawing.polylines)} polylines, {points:,} points,"
             f" {ntext} label{'' if ntext == 1 else 's'}\n")
    if _is_alternate(name):
        # The rotated file exists for machines whose HP-GL X axis runs along
        # the feed. Quoting a paper width derived from its X extent would be
        # actively misleading, so state the relationship instead.
        line = (f"  {name}\n"
                f"      [ALTERNATE] the same marker turned 90 degrees.\n"
                f"      Use ONLY if the standard file above prints turned the\n"
                f"      wrong way. The finished marker is the same size either\n"
                f"      way: {min(w, h):.0f} mm across by {max(w, h):.0f} mm long.\n"
                + stats)
    else:
        line = (f"  {name}\n"
                f"      plots {w:.1f} x {h:.1f} mm"
                f"   -- needs paper >= {w + 40.0:.0f} mm wide\n"
                + stats)
    return line, (w, h)


def _is_alternate(name):
    """Rotated variants are alternatives, not additional work to print."""
    return "rotat" in name.lower() or "alternate" in name.lower()


def main(argv=None):
    p = argparse.ArgumentParser(
        prog="handover",
        description="Write a spec sheet describing a set of .plt files.")
    p.add_argument("inputs", nargs="+", help="the .plt files being sent")
    p.add_argument("-o", "--output", default="READ ME - plotter spec.txt",
                   help="output path")
    args = p.parse_args(argv)

    lines, sizes, cal, test, alternates = [], [], "", "", []
    for path in args.inputs:
        try:
            line, size = describe(path)
        except OSError as exc:
            print(f"handover: error: {exc}", file=sys.stderr)
            return 1
        if line is None:
            print(f"handover: warning: {path} has no geometry, skipped",
                  file=sys.stderr)
            continue
        lines.append(line)
        sizes.append(size)
        name = os.path.basename(path)
        if "calib" in name.lower():
            cal = name
        elif "test" in name.lower():
            test = name
        if _is_alternate(name):
            alternates.append(name)

    if not lines:
        print("handover: error: no readable .plt files given", file=sys.stderr)
        return 1

    pens = "".join(
        f"  Pen {pen}   {kind}\n"
        for kind, pen in sorted(classify.DEFAULT_PENS.items(), key=lambda x: x[1])
        if kind != classify.UNKNOWN
    )
    if alternates:
        orient = (
            "\nBoth orientations are supplied, so please do NOT rotate anything in\n"
            "your software -- use the file that fits. A RIP that rotates sometimes\n"
            "rescales as well, which would silently change the pattern size.\n")
    else:
        orient = (
            "\nIf a file plots turned the wrong way, please say so rather than\n"
            "rotating it in your software -- a RIP that rotates sometimes rescales\n"
            "as well. A pre-rotated file can be supplied instead.\n")

    text = TEMPLATE.format(
        underline="=" * 26,
        files="".join(lines),
        pens=pens,
        cal=cal or "the calibration file",
        test=test or "the single-piece test file",
        orient=orient,
    )
    with open(args.output, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"wrote  {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
